In [2]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

import warnings
warnings.filterwarnings("ignore")

In [3]:
import os

In [4]:
os.getcwd()

'/Users/rajatsuri'

In [5]:
#define working directory
os.chdir('/Users/rajatsuri/Desktop/Padhai/CIS 508/assignment2')

In [6]:
os.getcwd()

'/Users/rajatsuri/Desktop/Padhai/CIS 508/assignment2'

In [7]:
Train = pd.read_csv ('Insurance Fraud - TRAIN-3000(1).csv')
Test = pd.read_csv('Insurance Fraud -TEST-12900(1).csv')

In [8]:
Train.head()

,MONTH,WEEKOFMONTH,DAYOFWEEK,MAKE,ACCIDENTAREA,DAYOFWEEKCLAIMED,MONTHCLAIMED,WEEKOFMONTHCLAIMED,SEX,MARITALSTATUS,...,AGEOFPOLICYHOLDER,POLICEREPORTFILED,WITNESSPRESENT,AGENTTYPE,NUMBEROFSUPPLIMENTS,ADDRESSCHANGE_CLAIM,NUMBEROFCARS,YEAR,BASEPOLICY,FRAUDFOUND
0,Jul,3,Sunday,Honda,Rural,Wednesday,Jan,4,Male,Married,...,26_to_30,No,No,External,3_to_5,no_change,1-vehicle,1994,Collision,Yes
1,Nov,5,Monday,Mazda,Urban,Wednesday,Dec,1,Male,Single,...,over_65,No,No,External,none,no_change,1-vehicle,1994,All_Perils,Yes
2,Jan,1,Monday,Pontiac,Urban,Wednesday,Jan,1,Male,Married,...,41_to_50,No,No,External,none,under_6_months,1-vehicle,1994,All_Perils,Yes
3,Dec,1,Monday,Toyota,Rural,Tuesday,May,3,Male,Married,...,36_to_40,No,No,External,more_than_5,under_6_months,2-vehicles,1994,All_Perils,Yes
4,Dec,5,Wednesday,Pontiac,Urban,Wednesday,Jan,1,Male,Single,...,36_to_40,No,No,External,more_than_5,no_change,1-vehicle,1994,Collision,Yes

In [9]:
Test.head()

,MONTH,WEEKOFMONTH,DAYOFWEEK,MAKE,ACCIDENTAREA,DAYOFWEEKCLAIMED,MONTHCLAIMED,WEEKOFMONTHCLAIMED,SEX,MARITALSTATUS,...,AGEOFPOLICYHOLDER,POLICEREPORTFILED,WITNESSPRESENT,AGENTTYPE,NUMBEROFSUPPLIMENTS,ADDRESSCHANGE_CLAIM,NUMBEROFCARS,YEAR,BASEPOLICY,FRAUDFOUND
0,Jul,3,Sunday,Honda,Rural,Wednesday,Jan,4,Male,Married,...,26_to_30,No,No,External,3_to_5,no_change,1-vehicle,1994,Collision,Yes
1,Nov,5,Monday,Mazda,Urban,Wednesday,Dec,1,Male,Single,...,over_65,No,No,External,none,no_change,1-vehicle,1994,All_Perils,Yes
2,Jan,1,Monday,Pontiac,Urban,Wednesday,Jan,1,Male,Married,...,41_to_50,No,No,External,none,under_6_months,1-vehicle,1994,All_Perils,Yes
3,Dec,1,Monday,Toyota,Rural,Tuesday,May,3,Male,Married,...,36_to_40,No,No,External,more_than_5,under_6_months,2-vehicles,1994,All_Perils,Yes
4,Dec,5,Wednesday,Pontiac,Urban,Wednesday,Jan,1,Male,Single,...,36_to_40,No,No,External,more_than_5,no_change,1-vehicle,1994,Collision,Yes

In [10]:
Train.shape

(2999, 32)

Train.dtypes

In [11]:
Train.dtypes

MONTH                   object
WEEKOFMONTH              int64
DAYOFWEEK               object
MAKE                    object
ACCIDENTAREA            object
DAYOFWEEKCLAIMED        object
MONTHCLAIMED            object
WEEKOFMONTHCLAIMED       int64
SEX                     object
MARITALSTATUS           object
AGE                      int64
FAULT                   object
POLICYTYPE              object
VEHICLECATEGORY         object
VEHICLEPRICE            object
REPNUMBER                int64
DEDUCTIBLE               int64
DRIVERRATING             int64
DAYS_POLICY_ACCIDENT    object
DAYS_POLICY_CLAIM       object
PASTNUMBEROFCLAIMS      object
AGEOFVEHICLE            object
AGEOFPOLICYHOLDER       object
POLICEREPORTFILED       object
WITNESSPRESENT          object
AGENTTYPE               object
NUMBEROFSUPPLIMENTS     object
ADDRESSCHANGE_CLAIM     object
NUMBEROFCARS            object
YEAR                     int64
BASEPOLICY              object
FRAUDFOUND              object
dtype: object

In [12]:
Train.isnull().sum()

MONTH                   0
WEEKOFMONTH             0
DAYOFWEEK               0
MAKE                    0
ACCIDENTAREA            0
DAYOFWEEKCLAIMED        0
MONTHCLAIMED            0
WEEKOFMONTHCLAIMED      0
SEX                     0
MARITALSTATUS           0
AGE                     0
FAULT                   0
POLICYTYPE              0
VEHICLECATEGORY         0
VEHICLEPRICE            0
REPNUMBER               0
DEDUCTIBLE              0
DRIVERRATING            0
DAYS_POLICY_ACCIDENT    0
DAYS_POLICY_CLAIM       0
PASTNUMBEROFCLAIMS      0
AGEOFVEHICLE            0
AGEOFPOLICYHOLDER       0
POLICEREPORTFILED       0
WITNESSPRESENT          0
AGENTTYPE               0
NUMBEROFSUPPLIMENTS     0
ADDRESSCHANGE_CLAIM     0
NUMBEROFCARS            0
YEAR                    0
BASEPOLICY              0
FRAUDFOUND              0
dtype: int64

In [13]:
Train.describe()

,WEEKOFMONTH,WEEKOFMONTHCLAIMED,AGE,REPNUMBER,DEDUCTIBLE,DRIVERRATING,YEAR
count,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000,2999.000000
mean,2.781260,2.671224,40.055352,8.511837,407.302434,2.496832,1995.114038
std,1.286055,1.261614,13.497026,4.601437,41.847258,1.118365,0.606007
min,1.000000,1.000000,0.000000,1.000000,300.000000,1.000000,1994.000000
25%,2.000000,2.000000,31.000000,4.000000,400.000000,1.000000,1995.000000
50%,3.000000,3.000000,38.000000,9.000000,400.000000,2.000000,1995.000000
75%,4.000000,4.000000,49.000000,12.000000,400.000000,3.000000,1995.000000
max,5.000000,5.000000,80.000000,16.000000,700.000000,4.000000,1996.000000

In [15]:
# seperating input data and data we want to predict
inputs = Train.drop('FRAUDFOUND', axis='columns')
target = Train['FRAUDFOUND']

In [18]:
#list of categorical features that need onehot encoding 
categoricalFeatures =['MONTH',
'DAYOFWEEK',
'MAKE',
'ACCIDENTAREA',
'DAYOFWEEKCLAIMED',
'MONTHCLAIMED',
'SEX',
'MARITALSTATUS',
'FAULT',
'POLICYTYPE',
'VEHICLECATEGORY',
'VEHICLEPRICE',
'DAYS_POLICY_ACCIDENT',
'DAYS_POLICY_CLAIM',
'PASTNUMBEROFCLAIMS',
'AGEOFVEHICLE',
'AGEOFPOLICYHOLDER',
'POLICEREPORTFILED',
'WITNESSPRESENT',
'AGENTTYPE',
'NUMBEROFSUPPLIMENTS',
'ADDRESSCHANGE_CLAIM',
'NUMBEROFCARS',
'BASEPOLICY']

In [19]:
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(inputs[categoricalFeatures]),columns=ohe.get_feature_names(),index=inputs.index)

In [20]:
inputs = pd.concat([inputs,Xcat],axis=1)

In [21]:
inputs.drop(labels=categoricalFeatures,axis=1,inplace=True)

In [22]:
inputs.sample(5)

,WEEKOFMONTH,WEEKOFMONTHCLAIMED,AGE,REPNUMBER,DEDUCTIBLE,DRIVERRATING,YEAR,x0_Apr,x0_Aug,x0_Dec,...,x21_4_to_8_years,x21_no_change,x21_under_6_months,x22_1-vehicle,x22_2-vehicles,x22_3_to_4,x22_5_to_8,x23_All_Perils,x23_Collision,x23_Liability
1228,3,4,50,11,400,4,1995,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
803,2,3,55,9,400,4,1995,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
554,4,4,27,7,400,3,1994,0.0,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
403,2,2,43,11,400,4,1994,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1072,4,5,78,4,400,3,1995,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [23]:
Test.head()

,MONTH,WEEKOFMONTH,DAYOFWEEK,MAKE,ACCIDENTAREA,DAYOFWEEKCLAIMED,MONTHCLAIMED,WEEKOFMONTHCLAIMED,SEX,MARITALSTATUS,...,AGEOFPOLICYHOLDER,POLICEREPORTFILED,WITNESSPRESENT,AGENTTYPE,NUMBEROFSUPPLIMENTS,ADDRESSCHANGE_CLAIM,NUMBEROFCARS,YEAR,BASEPOLICY,FRAUDFOUND
0,Jul,3,Sunday,Honda,Rural,Wednesday,Jan,4,Male,Married,...,26_to_30,No,No,External,3_to_5,no_change,1-vehicle,1994,Collision,Yes
1,Nov,5,Monday,Mazda,Urban,Wednesday,Dec,1,Male,Single,...,over_65,No,No,External,none,no_change,1-vehicle,1994,All_Perils,Yes
2,Jan,1,Monday,Pontiac,Urban,Wednesday,Jan,1,Male,Married,...,41_to_50,No,No,External,none,under_6_months,1-vehicle,1994,All_Perils,Yes
3,Dec,1,Monday,Toyota,Rural,Tuesday,May,3,Male,Married,...,36_to_40,No,No,External,more_than_5,under_6_months,2-vehicles,1994,All_Perils,Yes
4,Dec,5,Wednesday,Pontiac,Urban,Wednesday,Jan,1,Male,Single,...,36_to_40,No,No,External,more_than_5,no_change,1-vehicle,1994,Collision,Yes

In [24]:
Xcat = pd.DataFrame(ohe.transform(Test[categoricalFeatures]),columns=ohe.get_feature_names(),index=Test.index)

In [25]:
# OneHotEncoding on Test (only transform)
# OneHotEncoding is to be done on Categorical variables.
Xcat = pd.DataFrame(ohe.transform(Test[categoricalFeatures]),columns=ohe.get_feature_names(),index=Test.index)
Test = pd.concat([Test,Xcat],axis=1)
Test.drop(labels=categoricalFeatures,axis=1,inplace=True)
Test.sample(5)

,WEEKOFMONTH,WEEKOFMONTHCLAIMED,AGE,REPNUMBER,DEDUCTIBLE,DRIVERRATING,YEAR,FRAUDFOUND,x0_Apr,x0_Aug,...,x21_4_to_8_years,x21_no_change,x21_under_6_months,x22_1-vehicle,x22_2-vehicles,x22_3_to_4,x22_5_to_8,x23_All_Perils,x23_Collision,x23_Liability
12301,3,4,67,6,400,3,1994,No,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
12246,2,4,32,12,400,3,1996,No,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
6382,5,2,49,14,400,3,1994,No,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4144,3,3,27,4,400,1,1994,No,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
5551,3,3,27,6,400,3,1995,No,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [26]:
from sklearn import tree
from sklearn import set_config

In [27]:
#Decision Tree Model
modelDF = tree.DecisionTreeClassifier()

In [28]:
#Fitting the model on train data
DF = modelDF.fit(inputs,target)

In [29]:
print(modelDF.fit(inputs,target))
set_config(print_changed_only=True)

DecisionTreeClassifier()

In [30]:
rf = RandomForestClassifier()

In [31]:
rf.fit(inputs, target)

RandomForestClassifier()

In [32]:
print(rf.fit(inputs, target))
set_config(print_changed_only=True)

RandomForestClassifier()

In [34]:
# seperating input data and data we want to predict
Xtest = Test.drop('FRAUDFOUND', axis='columns')
Ytest = Test['FRAUDFOUND']

In [35]:
X_Pred = modelDF.predict(Xtest)
XPred = modelDF.predict(inputs)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(target,XPred))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred))
print("Max Depth",modelDF.get_depth())
print("Leaf",modelDF.get_n_leaves())
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred))

Train Accuracy: 1.0
Test Accuracy: 0.8824895494658616
Confusion Matrix for Decision Tree:
[[10950  1470]
 [   48   450]]
Max Depth 24
Leaf 289
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       1.00      0.88      0.94     12420
         Yes       0.23      0.90      0.37       498

    accuracy                           0.88     12918
   macro avg       0.62      0.89      0.65     12918
weighted avg       0.97      0.88      0.91     12918

In [36]:
X_Pred1 = rf.predict(Xtest)
XPred1 = rf.predict(inputs)
#Model Accuracy
print("Train Accuracy:", metrics.accuracy_score(target,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_Pred1))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,X_Pred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_Pred1))

Train Accuracy: 1.0
Test Accuracy: 0.9653971202972597
Confusion Matrix for Decision Tree:
[[12051   369]
 [   78   420]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.99      0.97      0.98     12420
         Yes       0.53      0.84      0.65       498

    accuracy                           0.97     12918
   macro avg       0.76      0.91      0.82     12918
weighted avg       0.98      0.97      0.97     12918

In [39]:
#Hyperparameter tuning done for decision tree classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth': 
            range(26,41,2),'criterion':['gini']}
dt_random = RandomizedSearchCV(modelDF,parameters,n_iter=25,cv=5)
dt_random.fit(inputs, target)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 50, 'max_depth': 30, 'criterion': 'gini'}
accuracy Score for Decision Tree:0.884115
--- 3.5453040599823 seconds ---

In [40]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(modelDF,parameters)
dt_grid.fit(inputs, target)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree
{'criterion': 'gini', 'max_depth': 26, 'min_samples_leaf': 30}
accuracy Score for Decision Tree:0.897430
--- 30.31842613220215 seconds ---

In [41]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier 
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(inputs,target)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(inputs,target)
dtGrid_predict = dtGrid.predict(Xtest)

In [42]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
clf_cv_score = cross_val_score(dtRand, inputs, target, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.8841151881096145
Confusion Matrix for Decision Tree:
[[11255  1165]
 [  332   166]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.91      0.94     12420
         Yes       0.12      0.33      0.18       498

    accuracy                           0.88     12918
   macro avg       0.55      0.62      0.56     12918
weighted avg       0.94      0.88      0.91     12918

[0.74903846 0.72307692 0.54375    0.5        0.57594937]

In [43]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')

Test Accuracy: 0.8974299427155906
Confusion Matrix for Decision Tree:
[[11427   993]
 [  332   166]]
Printing the precision and recall, among other metrics

In [44]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth': 
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(inputs, target)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest
{'n_estimators': 30, 'min_samples_leaf': 20, 'max_features': 30, 'max_depth': 9}
accuracy Score for Decision Tree:0.929014
--- 13.884265899658203 seconds ---

In [45]:
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(inputs, target)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Random Forest
{'max_depth': 9, 'max_features': 30, 'min_samples_leaf': 20, 'n_estimators': 40}
accuracy Score for Decision Tree:0.931491
--- 293.29285407066345 seconds ---

In [49]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier 
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(inputs,target)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(inputs,target)
rfGrid_predict = rfGrid.predict(Xtest)

In [51]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
clf_cv_score = cross_val_score(rfRand, inputs, target, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9331165815141663
Confusion Matrix for Decision Tree:
[[11939   481]
 [  383   115]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.96      0.97     12420
         Yes       0.19      0.23      0.21       498

    accuracy                           0.93     12918
   macro avg       0.58      0.60      0.59     12918
weighted avg       0.94      0.93      0.94     12918

[0.75240385 0.72788462 0.54375    0.5        0.55696203]

In [50]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))

Test Accuracy: 0.9266140269391546
Confusion Matrix for Decision Tree:
[[11849   571]
 [  377   121]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.95      0.96     12420
         Yes       0.17      0.24      0.20       498

    accuracy                           0.93     12918
   macro avg       0.57      0.60      0.58     12918
weighted avg       0.94      0.93      0.93     12918